.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders__c</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/OrderService.cls
public class OrderService {
	public static List<Order__c> getAll() {
		try {
			List<Order__c> orderList =
			[SELECT Name, AccountId__c, TotalProductCount__c, TotalPrice__c FROM Order__c];
			return orderList;
		} catch (QueryException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static Order__c getByName(String name) {
		try {
			Order__c order =
			[SELECT Name, AccountId__c, TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Name = :name Limit 1];
			return order;
		} catch (QueryException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static Order__c getById(Id id) {
		try {
			Order__c order =
			[SELECT Name, AccountId__c, TotalProductCount__c, TotalPrice__c FROM Order__c WHERE Id = :id Limit 1];
			return order;
		} catch (QueryException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void create(Order__c order) {
		try {
			insert order;
		} catch (Exception e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void create(Order__c[] orders) {
		Set<Type> exList = new Set<Type> { DmlException.class, ListException.class };
		try {
			insert orders;
		} catch (Exception e) {
			if (!exList.contains(Type.forName(e.getTypeName()))) throw e;

			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void deleteById(Id id) {
		try {
			delete [select Id from Order__c where Id = :id];
		} catch (DmlException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void updateOrder(Order__c order) {
		try {
			update order;
		} catch (DmlException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

}