.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems__c</relationshipLabel>
        <relationshipName>OrderItems_c</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems__c</relationshipLabel>
        <relationshipName>OrderItems_c</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem__c</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems__c</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderItemService.cls
public class OrderItemService {

	public static List<OrderItem__c> getAll() {
		try {
			List<OrderItem__c> orderItemList =
			[SELECT Id, Name, OrderId__c, ProductId__c, Quantity__c, Price__c FROM OrderItem__c];

			return orderItemList;
		} catch (QueryException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static OrderItem__c getById(Id id) {
		try {
			OrderItem__c orderItem =
			[SELECT Name, OrderId__c, ProductId__c, Quantity__c, Price__c FROM OrderItem__c WHERE Id = :id Limit 1];
			return orderItem;
		} catch (QueryException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void create(OrderItem__c order) {
		Set<Type> exList = new Set<Type> { DmlException.class, NullPointerException.class };

		try {
			insert order;
		} catch (Exception e) {
			if (!exList.contains(Type.forName(e.getTypeName())))
				throw e;

			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void create(OrderItem__c[] orders) {
		Set<Type> exList = new Set<Type> { DmlException.class, ListException.class };
		try {
			insert orders;
		} catch (Exception e) {
			if (!exList.contains(Type.forName(e.getTypeName()))) throw e;

			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void deleteById(Id id) {
		try {
			delete [select Id from OrderItem__c where Id = :id];
		} catch (DmlException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}

	public static void updateOrder(OrderItem__c order) {
		try {
			update order;
		} catch (DmlException e) {
			System.debug(LoggingLevel.ERROR, e.getMessage());
			throw new HandledException(e.getMessage());
		}
	}
	
}