.apex/src/objects/Order__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders__c</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/objects/OrderItem__c.object
<CustomObject>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems__c</relationshipLabel>
        <relationshipName>OrderItems_c</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems__c</relationshipLabel>
        <relationshipName>OrderItems_c</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem__c</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems__c</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product__c</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products__c</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/OrderItemInsertTriggerTest.cls
@IsTest
private class OrderItemInsertTriggerTest {
	@IsTest
	static void testOrderItemInsert() {
		insert new Account(Name = 'TEST');
		Account account = [SELECT Id FROM Account WHERE Name = 'TEST'];
		insert new Order__c(Name = 'TEST', AccountId__c = account.Id, TotalProductCount__c = 0, TotalPrice__c = 0);
		Order__c order = [SELECT Id, Name, AccountId__c, TotalProductCount__c, TotalPrice__c  FROM Order__c WHERE Name = 'TEST'];
		insert new Product__c(Name = 'TEST', Price__c = 100);
		Product__c product = [SELECT Id, Price__c FROM Product__c WHERE Name = 'TEST'];

		OrderItem__c[] orderItems = new OrderItem__c[] {
				new OrderItem__c(
						OrderId__c = order.Id,
						ProductId__c = product.Id,
						Quantity__c = 1,
						Price__c = product.Price__c),
				new OrderItem__c(
						OrderId__c = order.Id,
						ProductId__c = product.Id,
						Quantity__c = 1,
						Price__c = product.Price__c),
				new OrderItem__c(
						OrderId__c = order.Id,
						ProductId__c = product.Id,
						Quantity__c = 1,
						Price__c = product.Price__c)
				};

		insert orderItems;

		Integer refQuantity = orderItems.size();
		Integer refPrice = (Integer)(product.Price__c * refQuantity);

		Order__c afterInsertOrder = [SELECT Id, TotalPrice__c, TotalProductCount__c FROM Order__c WHERE Name = 'TEST'];

		System.assertEquals(refPrice, afterInsertOrder.TotalPrice__c);
		System.assertEquals(refQuantity, afterInsertOrder.TotalProductCount__c);
	}
}